# Site settings
title: Geek for Brains
email: gavin@geekforbrains.com
description: >
  Hi, my names Gavin. I've been writing code for the better part of 10 years. 
  I co-founded Postach.io and QuoteRobot. When I'm not in front of my laptop, 
  you can probably find me adventuring in the outdoors.
baseurl: ""
url: "http://geekforbrains.com"
author: "Gavin Vickery"
twitter_url: "http://twitter.com/geekforbrains"
github_url: "http://github.com/geekforbrains"
instagram_url: "https://www.instagram.com/geekforbrains/"
linkedin_url: "https://ca.linkedin.com/in/geekforbrains"
disqus: geekforbrains
google_analytics: UA-1128393-15
paginate: 8
paginate_path: "/posts/:num"

# Build settings
gems: [jekyll-paginate, jekyll-redirect-from]
markdown: kramdown
